# Generated by Django 5.2 on 2026-06-22 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_detallecomprobante_producto_and_more'),
        ('inventario', '0002_alter_kardex_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenservicio',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FACTURADA', 'Facturada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='DetalleOrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('orden_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.ordenservicio')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Detalle Orden de Servicio',
                'verbose_name_plural': 'Detalles de Órdenes de Servicio',
            },
        ),
    ]
